### ISSUE TITLE
backup_to_git script doesn't run when there is a configuration change

### ISSUE THREAD

**Issue by aps-sids** [Tpbrown/ansible-gocd#17]
I want to run backup script only when there is a change in the config. As per the `README`, the sample pipeline
```
triggers a backup of Go every 10 minutes, or if the configuration changes
```
This doesn't seem to work for me. Also, I want to know that how does the script know that the config has been changed?

**Comment by patdowney** [comment]
You can probably do this by turning polling on for the `file:///var/lib/go-server/db/config` material and turning off the cron
